version: '3.8'

services:
  app:
    build: .
    container_name: ${APP_NAME:-nestjs-auth}
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: ${DB_HOST:-db}
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
